### ISSUE TITLE
Integration (sensor) error

### ISSUE THREAD

**Issue by sliwma** [PiotrMachowski/Home-Assistant-custom-components-iMPK#2]
BInary sensor with data works, or at least appears, but the sensors don't.
Logs:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/impk/sensor.py", line 42, in setup_platform
    raise Exception("Invalid stop id: {}".format(stop_id))
Exception: Invalid stop id: 11454
```

**Comment by PiotrMachowski** [comment]
You have provided an invalid stop ID, how did you get it?

**Comment by sliwma** [comment]
From the iMPK app. I didn't change the config for a while. I don't even know which stop is it to verify.

**Comment by PiotrMachowski** [comment]
It seems like the stop has been removed:
https://www.wroclaw.pl/przystanek-mielecka-linia-7-kierunek-poswietne-slupek-11454
