### ISSUE TITLE
"impk: Error on device update!"

### ISSUE THREAD

**Issue by sliwma** [PiotrMachowski/Home-Assistant-custom-components-iMPK#3]
Hey, the integration stopped working, except for information (binary sensor):
```
Logger: homeassistant.components.sensor
Source: custom_components/impk/sensor.py:188
Integration: Sensor (documentation, issues)
First occurred: 17:26:47 (16 occurrences)
Last logged: 17:26:53

impk: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/impk/sensor.py", line 107, in update
    delays = IMPKSensor.get_delays(courses, positions)
  File "/config/custom_components/impk/sensor.py", line 188, in get_delays
    for position in positions:
TypeError: 'NoneType' object is not iterable
```

**Comment by PiotrMachowski** [comment]
It should be fixed in v1.1.5
